#!/bin/sh
echo Starting X
Xvfb -listen tcp -nolisten local -nolisten unix :1 &
echo "sleep for 10 seconds to avoid race"
sleep 5
echo test | nc -v -w 1 127.0.0.1 6001
sleep 5
echo "Start the phantomjs"

sudo tcpdump -ln &
# retrieve the report
DISPLAY=127.0.0.1:1.0 strace phantomjs /tmp/retrieve.js

echo "Done with phantomjs, stopping X" >&2

# stop a dummy X11
kill %1

